<?php

namespace AppBundle\Repository;

/**
 * ProductRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
